### ISSUE TITLE
Installation readme problem

### ISSUE THREAD

**Issue by Raseth** [rolczynski/DeepSpeech-Keras#3]
Hi,

I've a problem with installation of your version of deepspeech. 
The
'''pip install deepspeech-keras'''
command doesn't work since there is no such package at pypi ( https://pypi.org/search/?q=deepspeech ) (or at least, I'm unable to find it).

Also there's a problem with alternative installation precedure, since there is no requirements.txt file in the repo (there is only environment.yml, which is usable by conda, however it's significantly harder to use deepspeech without conda (for example with pipenv)).

It'd be really helpful for pip install option to work, since there is only a few STT open-sourced tools with premade models : )

**Comment by rolczynski** [comment]
hey,
you are right. I will create the package at pypi (it's not done yet). The final pretrained models are not prepared now, they will be available in the next few weeks. if you are in a hurry, I could somehow help you

**Comment by charlesliucn** [comment]
Hi @rolczynski 
  I've also tried to run your scripts, but it seems the `requirements.txt` file mentioned in `README` is missing. Could you please check that?

**Comment by rolczynski** [comment]
Hey @charlesliucn 
I've changed the `README` and added new environment files. 

Give the feedback if still you have problems

**Comment by charlesliucn** [comment]
Thanks, and this project is great! :+1:
