### ISSUE TITLE
Log filterbank and keras version

### ISSUE THREAD

**Issue by bagustris** [rolczynski/DeepSpeech-Keras#5]
Hi,

I see you recently you change from MFCC to log filterbank for acoustic feature extraction. Is there any particular reason (improvement, etc)? Should it better to keep those two so user can choose and experimenting between those two feature extractions?

Also, as the main principle of your proposed platform is for easiness and understandable, isn't it better to keep to use Keras instead of tf.keras? I see it your to-do/contributing list.

**Comment by rolczynski** [comment]
hey!

the log filter banks (`logfbanks`) work as good as MFCC. This is a nice tutorial:

**Comment by rolczynski** [comment]
hey!

The log filter banks (logfbanks) work as good as MFCC. It is an excellent tutorial:
https://haythamfayek.com/2016/04/21/speech-processing-for-machine-learning.html
Especially:
" Learning in speech systems, one might question if MFCCs are still the right choice given that deep neural networks are less susceptible to highly correlated input and therefore the Discrete Cosine Transform (DCT) is no longer a necessary step. It is beneficial to note that Discrete Cosine Transform (DCT) is a linear transformation, and therefore undesirable as it discards some information in speech signals which are highly non-linear."

In most recent papers researchers do not use MFCC (harder to augmented etc.)

**Comment by bagustris** [comment]
Could you provide %WER comparison between MFCC and Log filterbank?

**Comment by rolczynski** [comment]
Unfortunately, I have not done comprehensive research about the difference between MFCC and log filter bank
