### ISSUE TITLE
Installation Conda

### ISSUE THREAD

**Issue by Stingray2020** [rolczynski/DeepSpeech-Keras#7]
Love the project . I'm looking to use this to adapt models to my voice. But I'm struggling on the installation process with conda. Getting a "Solving environment : Failed " message after running the command :

conda env create -f=environment.yml     

ResolvePackagesNotFound
scipy=1.1.0=py36h7c811a0_2
....... 
tensorflow=1.12.0=gpu_py36he74679b_0

Anyway Thank you keep up the good work :+1:

**Comment by rolczynski** [comment]
hey!

Thank you very much. The problem is connected with the GPU.  Please rename the line to `tensorflow=1.12.0`, and it should work. 

Rafal

**Comment by Stingray2020** [comment]
Hi rolczynski
Im really sorry I was running : 
conda env create -f=environment-gpu.yml

Ill attach my Error , as I tried to summarize it and confused 

![image](https://user-images.githubusercontent.com/7016493/62414267-e210e200-b610-11e9-83fd-79caf210a043.png)

I take its some of the packages cant be found on conda. Or I don't have the correct conda repos ?

Thank you spo much for the quick reply.

**Comment by rolczynski** [comment]
Hey! I've updated new environment files [over there](https://github.com/rolczynski/DeepSpeech-Keras/commit/ec317d6f19089744fda927e7b28180ac26645bf8) :+1:
